MVCCSharpProject/Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using MVCCSharpProject.ViewModels;

namespace MVCCSharpProject.Models
{
    public class Repository
    {

        public string _connectionString =
            System.Configuration.ConfigurationManager.ConnectionStrings["mvcCsharp"].ConnectionString;


        public void Create(Customers customerForm)
        {
            using (var connection = new SqlConnection(_connectionString))
            using (var command = connection.CreateCommand())
            {
                command.CommandText = @"INSERT INTO CustomersTable
                                                 (CustomerName,CustomerAddress,CustomerPhone)
                                         VALUES  (@CustomerName,@CustomerAddress,@CustomerPhone)";
                command.Parameters.AddWithValue("@CustomerName", customerForm.CustomerName);
                command.Parameters.AddWithValue("@CustomerAddress", customerForm.CustomerAddress);
                command.Parameters.AddWithValue("@CustomerPhone", customerForm.CustomerPhone);

                connection.Open();
                command.ExecuteNonQuery();
            }
        }


        // ADDED THIS CODE TO GET THE CUSTOMER SELECTED IN THE LIST AND WE WILL USE IT FOR THE DELETE OPERATION TOO.

        internal Customers GetCustomerForEdit(string ID)
        {
            using (var connection = new SqlConnection(_connectionString))
            using (var command = connection.CreateCommand())
            {
                command.CommandText = @"SELECT *
                                    FROM CustomersTable WHERE ID = @ID";

                command.Parameters.AddWithValue("@ID", ID);
                connection.Open();
                var reader = command.ExecuteReader();
                Customers customers = null;
                while (reader.Read())
                {
                    customers = new Customers();
                    customers.Id = (int)reader["Id"];
                    customers.CustomerName = reader["CustomerName"] as string;
                    customers.CustomerAddress = reader["CustomerAddress"] as string;
                    customers.CustomerPhone = reader["CustomerPhone"] as string;
                }
                return customers;
            }
        }




        // added this method to update customer

        internal void UpdateCustomer(Customers customer)
        {
            using (var connection = new SqlConnection(_connectionString))
            using (var command = connection.CreateCommand())
            {
                command.CommandText = @"Update customersTable set CustomerName =@CustomerName,
                                                                CustomerAddress=@CustomerAddress,
                                                                CustomerPhone =@CustomerPhone
                                      WHERE Id = @Id";

                command.Parameters.AddWithValue("@Id", customer.Id);
                command.Parameters.AddWithValue("@CustomerName", customer.CustomerName);
                command.Parameters.AddWithValue("@CustomerAddress", customer.CustomerAddress);
                command.Parameters.AddWithValue("@CustomerPhone", customer.CustomerPhone);
                connection.Open();
                command.ExecuteNonQuery();
            }
        }

        internal List<Customers> GetCustomerReport(string searchTerm)
        {
            using (var connection = new SqlConnection(_connectionString))
            using (var command = connection.CreateCommand())
            {
                command.CommandText = @"SELECT *
                                        FROM CustomersTable
                                        WHERE CustomerName LIKE @searchTerm";

                command.Parameters.AddWithValue("@searchTerm", searchTerm + "%%");
                connection.Open();
                var reader = command.ExecuteReader();
                var customers = new List<Customers>();
                while (reader.Read())
                {
                    Customers customersList = new Customers();
                    customersList.Id = (int)reader["Id"];
                    customersList.CustomerName = reader["CustomerName"] as string;
                    customersList.CustomerAddress = reader["CustomerAddress"] as string;
                    customersList.CustomerPhone = reader["CustomerPhone"] as string;
                    customers.Add(customersList);
                }
                return customers;
            }
        }

        internal List<Customers> GetCustomers()
        {

            using (var connection = new SqlConnection(_connectionString))
            using (var command = connection.CreateCommand())
            {
                command.CommandText = @"SELECT * FROM CustomersTable";

                connection.Open();

                var reader = command.ExecuteReader();
                var customers = new List<Customers>();

                while (reader.Read())
                {
                    var customerList = new Customers();
                    customerList.Id = (int)reader["Id"];
                    customerList.CustomerName = reader["CustomerName"] as string;
                    customerList.CustomerAddress = reader["CustomerAddress"] as string;
                    customerList.CustomerPhone = reader["CustomerPhone"] as string;
                    customers.Add(customerList);

                }
                return customers;
            }

        }
    }
}

MVCCSharpProject/ViewModels/Customers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCCSharpProject.ViewModels
{
    public class Customers
    {
        public int Id { get; set; }
        [Required]
        public string CustomerName { get; set; }
        [Required]
        public string CustomerAddress { get; set; }
        [Required]
        public string CustomerPhone { get; set; }
    }
}

MVCCSharpProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCCSharpProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCCSharpProject/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCCSharpProject.Models;
using MVCCSharpProject.ViewModels;


namespace MVCCSharpProject.Controllers
{
    public class MainController : Controller
    {

        Repository _repository  = new Repository();


        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Customers customerForm)
        {
            if (ModelState.IsValid)
            {
                _repository.Create(customerForm);
                TempData["Success"] = "Seccussfully Saved";
            }
            return View();
        }

        public ActionResult CustomersList()
        {
            var customers = _repository.GetCustomers();
            return View(customers);
        }

public ActionResult TestAction(){
return View();
}




        public ActionResult CustomersReport(string searchTerm)
        {
            var customersReport = _repository.GetCustomerReport(searchTerm);
            return View(customersReport);
        }




  // Added these two actions for update operation
        public ActionResult Update(string ID)
        {
            var customerInfo = _repository.GetCustomerForEdit(ID);
            return View(customerInfo);
        }

        [HttpPost]
        public ActionResult Update(Customers customer)
        {
            if (ModelState.IsValid)
            {
                _repository.UpdateCustomer(customer);
                TempData["Success"] = "Successfull Updated Customer";
            }
            return View();
        }
    }
}

MVCCSharpProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCCSharpProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCCSharpProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVCCSharpProject/Views/Main/Create.cshtml
@model MVCCSharpProject.ViewModels.Customers

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customers</h4>

        @if (TempData["Success"] != null)
        {
            <h3 class="alert alert-success">@TempData["Success"]</h3>
        }



        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerPhone, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-10">
                @Html.Partial("_CustomerDetails")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCCSharpProject/Views/Main/CustomersList.cshtml
@model IEnumerable<MVCCSharpProject.ViewModels.Customers>

@{
    ViewBag.Title = "CustomersList";
}

<h2>CustomersList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerPhone)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerPhone)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MVCCSharpProject/Views/Main/CustomersReport.cshtml
@model IEnumerable<MVCCSharpProject.ViewModels.Customers>

@{
    ViewBag.Title = "CustomersReport";
}

<h2>CustomersReport</h2>



<form method="get">
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-2">
                <input type="text" class="form-control" name="searchTerm" value="" />
            </div>

            <div class="col-md-2">
                <button type="submit" class="btn btn-info"> <i class="glyphicon glyphicon-search"></i> Search</button>
            </div>
        </div>
    </div>

</form>

<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerPhone)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerPhone)
            </td>
            <td>
                @Html.ActionLink("Edit", "Update", new { id = item.Id }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn fa fa-trash btn-primary" })
            </td>
        </tr>
    }

</table>

MVCCSharpProject/Views/Main/Update.cshtml
@model MVCCSharpProject.ViewModels.Customers

@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customers</h4>
        @if (TempData["Success"] != null)
        {
            <h3 class="alert alert-success">@TempData["Success"]</h3>
        }
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCCSharpProject/Views/Main/_CustomerDetails.cshtml
<div class="row">
    <div class="col-md-6">
        <input type="text" value="" class="form-control" />
    </div>
    <div class="col-md-6">
        <input type="text" value="" class="form-control" />
    </div>
</div>

MVCCSharpProject/Views/Shared/_Layout.cshtml
---=-<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Create", "Create", "Main")</li>
                    <li>@Html.ActionLink("Customers List", "CustomersReport", "Main")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>